CREATE DATABASE parkingDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE parkingDB;
-- Tabla Tarifa
CREATE TABLE Tarifa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL,
  precio_por_hora DECIMAL(10,2) NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Vehiculo
CREATE TABLE Vehiculo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  placa VARCHAR(15) NOT NULL UNIQUE,
  modelo VARCHAR(100),
  tipo VARCHAR(50) NOT NULL,
  ingreso DATETIME NOT NULL,
  salida DATETIME NULL,
  total_pagado DECIMAL(10,2) DEFAULT 0.00,
  activo BOOLEAN DEFAULT TRUE,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SHOW TABLES;
SELECT * FROM Vehiculo;
SELECT * FROM Tarifa;
