CREATE DATABASE IF NOT EXISTS parkingDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE parkingDB;

-- Tabla tarfia
CREATE TABLE IF NOT EXISTS Tarifa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL,
  precio_por_hora DECIMAL(10,2) NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla vehiculo
CREATE TABLE IF NOT EXISTS Vehiculo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  placa VARCHAR(15) NOT NULL UNIQUE,
  modelo VARCHAR(100),
  tipo VARCHAR(50) NOT NULL,
  ingreso DATETIME NOT NULL,
  salida DATETIME NULL,
  total_pagado DECIMAL(10,2) DEFAULT 0.00,
  activo BOOLEAN DEFAULT TRUE,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

